openapi: 3.0.1
info:
  title: CWMAPI
  description: Post/read questions, answers, and comments
  version: 1.0.0
servers:
- url: http://34.208.28.95:3000/msgstore/v1
paths:
  /spaces:
    get:
      summary: Gets one or more spaces
      description: Returns a list containing one or more spaces.
      parameters:
      - name: spaceId
        in: query
        description: One (comma-separated) object ID for each space to get.  If empty, all spaces will be retrieved
        required: false
        schema:
          type: string
      - name: depth
        in: query
        description: 0 = no nesting, 1 = 1st order nesting, etc.  -1 for all levels.
        required: false
        schema:
          type: integer      
      responses:
        200:
          description: A list of spaces
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Space'
                  

  /questions:
    get:
      summary: Gets 0 or more questions based on query
      parameters:
      - name: spaceId
        in: query
        description: one or more (coma-separated) space _id.  If set, only questions from specified spaceId(s) will be returned
        required: false
        schema:
          type: string
      - name: questionId
        in: query
        description: One or more (comma-separated) question _id as a filter for questions, for each space to get.  If empty, all questions will be retrieved, based on the value if spaceId
        required: false
        schema:
          type: string

      - name: depth
        in: query
        description: 0 = no nesting, 1 = 1st order nesting, etc.  -1 for all levels.
        required: false
        schema:
          type: integer
      responses:
        200:
          description: A list of questions for a space
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Question'
                  

    post:
      summary: post a question to a space
      parameters:
      - name: spaceId
        in: query
        description: The space to post the question into
        required: true
        schema:
          type: string

      description: Adds a new question to a space.
      operationId: postQuestion
      requestBody:
        description: Question to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewQuestion'
      responses:
        200:
          description: question posted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Question'
        400:
          description: invalid format, for example, bad ObjectId or incorrect schema
          content:
            text/plain:
              schema:
                type: string
        404:
          description: spaceId is not found
          content:
            text/plain:
              schema:
                type: string


  /answers:
    get:
      summary: Gets one or more answers
      parameters:
      - name: questionId
        in: query
        description: one or more (coma-separated) question _id.  If set, only answers from specified questioId(s) will be returned
        required: true
        schema:
          type: string
      - name: answerId
        in: query
        description: One or more (comma-separated) answer _id as a filter for answers, for each question to get.  If empty, all answers will be retrieved, based on the value if questionId
        required: false
        schema:
          type: string
      - name: depth
        in: query
        description: 0 = no nesting, 1 = 1st order nesting, etc.  -1 for all levels.
        required: false
        schema:
          type: integer
      responses:
        200:
          description: A list of answers for a question
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Answer'

    post:
      summary: post an answer to a question
      parameters:
      - name: questionid
        in: query
        description: The question to be answered
        required: true
        schema:
          type: string

      description: Answers a question.
      operationId: postAnswer
      requestBody:
        description: Answer to question
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewAnswer'
      responses:
        200:
          description: answer posted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Answer'
        400:
          description: invalid format, for example, bad ObjectId or incorrect schema
          content:
            text/plain:
              schema:
                type: string
        404:
          description: questionId is not found
          content:
            text/plain:
              schema:
                type: string



  /comments:
    get:
      summary: Gets all top-level comments for an answer
      parameters:
      - name: answerId
        in: query
        description: one or more (coma-separated) answer _id.  If set, only coments from specified answer(s) will be returned
        required: true
        schema:
          type: string
      - name: commentId
        in: query
        description: One or more (comma-separated) comment _id as a filter for comments to get.  If empty, all commments will be retrieved, based on the value of answerId
        required: false
        schema:
          type: string
      - name: depth
        in: query
        description: 0 = no nesting, 1 = 1st order nesting, etc.  -1 for all levels.
        required: false
        schema:
          type: integer
      responses:
        200:
          description: A list of coments for an answer
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comment'
                  
    post:
      summary: post a comment to an answer
      parameters:
      - name: answerId
        in: query
        description: The _id of answer for comment
        required: false
        schema:
          type: string

      description: Comment for an answer.
      operationId: postComment
      requestBody:
        description: Comment 
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewComment'
      responses:
        200:
          description: comment posted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
        400:
          description: invalid format, for example, bad ObjectId or incorrect schema
          content:
            text/plain:
              schema:
                type: string
        404:
          description: answerId is not found
          content:
            text/plain:
              schema:
                type: string
                
  /reply:
    post:
      summary: post a reply to a comment
      parameters:
      - name: commentId
        in: query
        description: The _id of coment for reply
        required: false
        schema:
          type: string

      description: Reply for a comment.
      operationId: postReply
      requestBody:
        description: reply 
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewComment'
      responses:
        200:
          description: reply posted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
        400:
          description: invalid format, for example, bad ObjectId or incorrect schema
          content:
            text/plain:
              schema:
                type: string
        404:
          description: commentId is not found
          content:
            text/plain:
              schema:
                type: string

components:
  schemas:
    Space:
      required:
      - _id
      - createdOn
      - description
      - title
      type: object
      properties:
        _id:
          type: string
        title:
          type: string
        createdOn:
          type: string
          format: date-time
        description:
          type: string
        tags:
          type: array
          items:
            required:
            - tag
            type: object
            properties:
              tag:
                type: string
        questions:
          type: array
          items:
            required:
            - questions
            type: object
            properties:
              questions:
                $ref: '#/components/schemas/Question'
        
    Answer:
      required:
      - _id
      - answerText
      - createdBy
      - createdOn
      type: object
      properties:
        _id:
          type: string
        spaceId:
          type: string
        answerText:
          type: string
        createdOn:
          type: string
          format: date-time
        createdBy:
          type: string
        comments:
          type: array
          items:
            required:
            - comments
            type: object
            properties:
              replies:
                $ref: '#/components/schemas/Comment'
    NewAnswer:
      required:
      - userId
      - body
      properties:
        userId:
          type: string
        answerText:
          type: string
                
    Comment:
      required:
      - _id
      - answerId
      - commentText
      - createdBy
      - createdOn
      type: object
      properties:
        _id:
          type: string
        answerId:
          type: string
        parentCommentId:
          type: string
          description: The parent comment is for comment trees.  For first-gen comment,
            the parent is answer, and there is no parent comment.
        commentText:
          type: string
        createdOn:
          type: string
          format: date-time
        createdBy:
          type: string
        replies:
          type: array
          items:
            required:
            - replies
            type: object
            properties:
              replies:
                $ref: '#/components/schemas/Comment'

    NewComment:
      required:
      - userId
      - questionText
      properties:
        userId:
          type: string
        commentTex:
          type: string
          
    Question:
      required:
      - _id
      - questionText
      - createdBy
      - createdOn
      - spaceId
      type: object
      properties:
        _id:
          type: string
        spaceId:
          type: string
        questionText:
          type: string
        createdOn:
          type: string
          format: date-time
        createdBy:
          type: string
        answers:
          type: array
          items:
            required:
            - answers
            type: object
            properties:
              answers:
                $ref: '#/components/schemas/Answer'
    NewQuestion:
      required:
      - userId
      - questionText
      properties:
        userId:
          type: string
        questionText:
          type: string
                
    ObjectId:
      required:
      - _id
      type: object
      properties:
        _id:
          type: string
