/*
 * Cloud Walkers Message API
 *
 * Post/read questions, answers, and comments
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"log"
	"net/http"
	"os"
	"strings"
)

func main() {

	args := os.Args[1:]
	isLocal := false

	if(len(args)> 0){
		rq := strings.Split(args[0], "=")
		if(len(rq) == 2 && strings.Compare(rq[0], "DEBUG") == 0 && strings.Compare(strings.ToLower(rq[1]), "true") == 0){
			isLocal = true
		}
	}

	log.Printf("Server started")
	DbInit(isLocal);
	router := NewRouter()

	log.Fatal(http.ListenAndServe(":3000", router))
}
