/*
 * Cloud Walkers Message API
 *
 * Post/read questions, answers, and comments
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"log"
	"net/http"
)

func main() {


	log.Printf("Server started")
	DbInit();
	router := NewRouter()


	log.Fatal(http.ListenAndServe(":3000", router))
}
