/*
 * Cloud Walkers Message API
 *
 * Post/read questions, answers, and comments
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"gopkg.in/mgo.v2/bson"
	"time"
)

type Space struct {

	Id  bson.ObjectId `json:"_id" bson:"_id"`

	Title string `json:"title"`

	CreatedOn time.Time `json:"createdOn"`

	Description string `json:"description"`

	Tags []SpaceTags `json:"tags"`

	Questions []Question `json:"questions,omitempty"`
}
