/*
 * Cloud Walkers Message API
 *
 * Post/read questions, answers, and comments
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"time"
	"gopkg.in/mgo.v2/bson"
)

type Comment struct {

	Id  bson.ObjectId `json:"_id" bson:"_id"`

	AnswerId bson.ObjectId `json:"answerId" bson:"answerId"`

	// The parent comment is for comment trees.  For first-gen comment, the parent is answer, and there is no parent comment.
	ParentCommentId bson.ObjectId `json:"parentCommentId,omitempty" bson:"parentCommentId"`

	Body string `json:"body"`

	CreatedOn time.Time `json:"createdOn"`

	CreatedBy string `json:"createdBy"`

	Replies []Comment `json:"replies,omitempty"`
}
