/*
 * Cloud Walkers Message API
 *
 * Post/read questions, answers, and comments
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"gopkg.in/mgo.v2/bson"
	"time"
)

type Question struct {

	Id  bson.ObjectId `json:"_id" bson:"_id"`

	SpaceId bson.ObjectId `json:"spaceId" bson:"spaceId"`

	Body string `json:"body"`

	CreatedOn time.Time `json:"createdOn"`

	CreatedBy bson.ObjectId `json:"createdBy" bson:"createdBy"`

	Answers []Answer `json:"answers,omitempty"`
}
