/*
 * Cloud Walkers Message API
 *
 * Post/read questions, answers, and comments
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"github.com/codegangsta/negroni"
	"github.com/rs/cors"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewServer() *negroni.Negroni {

	corsObj := cors.New(cors.Options{
		AllowedOrigins: []string{"*"},
		AllowedMethods: []string{"POST", "GET", "OPTIONS", "PUT", "DELETE"},
		AllowedHeaders: []string{"Accept", "content-type", "Content-Length", "Accept-Encoding", "X-CSRF-Token", "Authorization"},
	})

	n := negroni.Classic()
	mx := NewRouter()
	n.Use(corsObj)
	n.UseHandler(mx)
	return n
}

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}


var routes = Routes{
	Route{
		"ping",
		"GET",
		"/msgstore/v1/ping",
		Ping,
	},

	{
		"GetTopics",
		strings.ToUpper("Get"),
		"/msgstore/v1/topics",
		GetTopics,
	},

	Route{
		"GetQuestions",
		strings.ToUpper("Get"),
		"/msgstore/v1/questions",
		GetQuestions,
	},

	{
		"PostQuestion",
		strings.ToUpper("Post"),
		"/msgstore/v1/questions",
		PostQuestion,
	},

	{
		"PutQuestionUpdate",
		strings.ToUpper("Put"),
		"/msgstore/v1/questions",
		PutQuestionUpdate,
	},

	{
		"GetAnswers",
		strings.ToUpper("Get"),
		"/msgstore/v1/answers",
		GetAnswers,
	},


	{
		"PostAnswer",
		strings.ToUpper("Post"),
		"/msgstore/v1/answers",
		PostAnswer,
	},

	{
		"PutAnswerUpdate",
		strings.ToUpper("Put"),
		"/msgstore/v1/answers",
		PutAnswerUpdate,
	},

	{
		"GetComments",
		strings.ToUpper("Get"),
		"/msgstore/v1/comments",
		GetComments,
	},

	{
		"PostComment",
		strings.ToUpper("Post"),
		"/msgstore/v1/comments",
		PostComment,
	},

	{
		"PostReply",
		strings.ToUpper("Post"),
		"/msgstore/v1/reply",
		PostReply,
	},

	{
		"PutCommentUpdate",
		strings.ToUpper("Put"),
		"/msgstore/v1/comments",
		PutCommentUpdate,
	},
	{
		"putUpdateCache",
		strings.ToUpper("Put"),
		"/msgstore/v1/flushcache",
		FlushCache,
	},

}
